name: Bug Report
description: Used to report an issue with the program.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - atcosner
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Upload Screenshots
      description: Please upload screenshots of the program if you believe they would assist in debugging the issue.
  - type: textarea
    id: logs
    attributes:
      label: Upload Log File
      description: Please upload the log file referenced in the Eagle Eye bug reporter
