on:
  push:
    tags:
      - "v*.*"

jobs:
  build-installer-windows:
    runs-on: windows-latest
    steps:
      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'eagle_eye.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Eagle Eye.exe'
