on:
  push:
    tags:
      - v*.*

jobs:
  build-installer-matrix:
    strategy:
      matrix:
        os: ['windows-latest'] # , 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build Eagle Eye Executable
        uses: sayyid5416/pyinstaller@v1
        if: github.ref == 'refs/heads/main'
        with:
          python_ver: '3.12'
          spec: 'eagle_eye.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Eagle Eye'
